### ISSUE TITLE
Documentation for using Passenger without any Ruby web framework?

### ISSUE THREAD

**Issue by jjgh** [phusion/passenger_library#7]
Is it possible to use passenger in a way it simply handles ruby code inside an HTML file, without using any Ruby framework at all?

**Comment by FooBarWidget** [comment]
No, we do not support that use case.

**Comment by jjgh** [comment]
I managed to make it work very easily using https://github.com/migrs/rack-server-pages . We know that having all the code in the View is wrong most of the times, but for super small tasks it might be very convenient. Maybe you could add a small section about this to the guide? People are constantly searching for a way to do that. StackOverflow is full of that kind of questions...

**Comment by FooBarWidget** [comment]
I'm wary of adding it because although some people undoubtedly want this, I doubt there are many of them compared to the total amount of users. But where in the library do you suggest adding this? I can't think of a place to add this that is easy to find for people who are looking for this, without at the same time annoying people who aren't looking for this.

**Comment by jjgh** [comment]
Not sure where, but I would add it...
